import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import DashboardNavbar from "../components/DashboardNavbar";
import DashboardContent from "../components/DashboardContent";
import Footer from "../components/Footer";

const Dashboard: React.FC = () => {
    return (
        <div className="body">
            <Head>
                <title>AI Reviewer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardNavbar />
            <DashboardContent />
            <Footer />
        </div>
    );
}

export default Dashboard;