import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import MainNavbar from "../components/Navbar";
import Content from "../components/Content";
import Footer from "../components/Footer";
import coreConstants from "../pages/core.Constants";

const Home: React.FC = () => {
  return (
    <div className="body">
      <Head>
          <title>{coreConstants.title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNavbar />
      <Content />
      <Footer />
    </div>
  );
}

export default Home;